test:
  allowed_origins:
    - http://localhost:3000

development:
  allowed_origins:
    - http://localhost:3000

staging:
  allowed_origins:
    - http://localhost:3000

production:
  allowed_origins:

