name: API Pipeline
on:
  push:
    branches:
      - main
    paths:
      - canix-api/**
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
        with:
          ruby-version: 3.0
      - name: Build project
        run: cd canix-api && make build
      - name: Static analysis
        run: cd canix-api && make lint
